{% set name = "dask-awkward" %}
{% set version = "2022.10a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_awkward/dask_awkward-{{ version }}.tar.gz
  sha256: c46735cf5acf64b65b63037598abb22df118e9f9f71f89091b4dc697137bd54f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.8.0
    - hatch-vcs
    - toml
  run:
    - python >=3.8
    - awkward >=1.10.1
    - dask >=2022.02.1

test:
  imports:
    - dask_awkward

about:
  home: https://dask-awkward.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Connecting awkward-array and Dask.
  description: |
    dask-awkward provides a native Dask collection representing
    partitioned awkward arrays.
  doc_url: https://dask-awkward.readthedocs.io/
  dev_url: https://github.com/ContinuumIO/dask-awkward/

extra:
  recipe-maintainers:
    - douglasdavis
    - martindurant
