{% set name = "dask-awkward" %}
{% set version = "2023.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_awkward/dask_awkward-{{ version }}.tar.gz
  sha256: c3c794d6f4ba384a78a9d43c5e2419b5c39caf0fe4dc04528e35050a952f4f0b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.8.0
    - hatch-vcs
    - toml
  run:
    - python >=3.8
    - awkward >=2.5.0
    - dask >=2023.04.0
    - typing_extensions

test:
  imports:
    - dask_awkward

about:
  home: https://dask-awkward.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Connecting awkward-array and Dask.
  description: |
    dask-awkward provides a native Dask collection representing
    partitioned awkward arrays.
  doc_url: https://dask-awkward.readthedocs.io/
  dev_url: https://github.com/dask-contrib/dask-awkward/

extra:
  recipe-maintainers:
    - agoose77
    - douglasdavis
    - martindurant
